# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: tech.shawna jean
email: hello@shawnajroberts.com
description: yelling at the void
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tech.shawnajean.tech" # the base hostname & protocol for your site
home: "http://shawnajean.tech"
paginate: 5
paginate_path: /:num
timezone: America/New_York
permalink: /:slug

site_heading: >
    tech<span class="faded">.shawna jean</span>


# Build settings
markdown: kramdown

gems:
    - jekyll-paginate
    - jekyll-feed

sass:
    style: compressed
    sass_dir: _sass

# Scopes
defaults:
    -
        scope:
            path:   ""
            type:   "pages"
        values:
            layout: "page"
    -
        scope:
            path:   ""
            type:   "posts"
        values:
            layout: "post"

exclude: [vendor] # For travis ci
